global using SharedKernel.Shared;
global using SharedKernel.Abstractions.Messaging;
global using Microsoft.Extensions.Logging;
global using SharedKernel.Abstractions;
global using InventoryService.Domain.Errors;
global using InventoryService.Domain.InventoryItems;
global using FluentValidation;
global using MediatR;
global using InventoryService.Application.Features.Inventory.Specifications;