apiVersion: v1
kind: Secret

metadata:
  name: ecommerce-secret
  namespace: ecommerce

type: Opaque

stringData:

  SA_PASSWORD: Password12345!

  RabbitMQ__Username: guest

  RabbitMQ__Password: guest

  SEQ_ADMIN_PASSWORD: Password123!