// <auto-generated />
using System;
using CancellationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CancellationService.Infrastructure.Migrations
{
    [DbContext(typeof(CancellationDbContext))]
    partial class CancellationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CancellationService.Domain.Cancellations.Cancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cancellations", (string)null);
                });

            modelBuilder.Entity("CancellationService.Infrastructure.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id", "Name");

                    b.HasIndex("Id", "Name");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("CancellationService.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("CancellationService.Domain.Cancellations.Cancellation", b =>
                {
                    b.OwnsOne("CancellationService.Domain.ValueObjects.Money", "Charges", b1 =>
                        {
                            b1.Property<Guid>("CancellationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CancellationCharges");

                            b1.HasKey("CancellationId");

                            b1.ToTable("Cancellations");

                            b1.WithOwner()
                                .HasForeignKey("CancellationId");
                        });

                    b.OwnsOne("CancellationService.Domain.ValueObjects.Money", "OrderAmount", b1 =>
                        {
                            b1.Property<Guid>("CancellationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OrderAmount");

                            b1.HasKey("CancellationId");

                            b1.ToTable("Cancellations");

                            b1.WithOwner()
                                .HasForeignKey("CancellationId");
                        });

                    b.OwnsOne("CancellationService.Domain.ValueObjects.Reason", "Reason", b1 =>
                        {
                            b1.Property<Guid>("CancellationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Reason");

                            b1.HasKey("CancellationId");

                            b1.ToTable("Cancellations");

                            b1.WithOwner()
                                .HasForeignKey("CancellationId");
                        });

                    b.OwnsOne("CancellationService.Domain.ValueObjects.Remarks", "Remarks", b1 =>
                        {
                            b1.Property<Guid>("CancellationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Remarks");

                            b1.HasKey("CancellationId");

                            b1.ToTable("Cancellations");

                            b1.WithOwner()
                                .HasForeignKey("CancellationId");
                        });

                    b.Navigation("Charges")
                        .IsRequired();

                    b.Navigation("OrderAmount")
                        .IsRequired();

                    b.Navigation("Reason")
                        .IsRequired();

                    b.Navigation("Remarks")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
